DeCharla/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('configuracion', views.manejar_configuracion, name='configuracion'),
    path('login', views.manejar_login, name='login'),
    path('logout', views.manejar_logout, name='logout'),
    path('help', views.help, name='help'),
    path('<str:sala>', views.manejar_salas, name='manejar_salas'),
    path('votar/', views.manejar_votos, name='manejar_votos'),
    path('desvotar/', views.manejar_votos, name='manejar_votos'),
    path('crear_sala/', views.crear_sala, name='crear_sala'),
    path('sala_json/<str:sala>', views.sala_json, name='sala_json'),
    path('sala_dinamica/<str:sala>', views.sala_dinamica, name='sala_dinamica'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.views.i18n import set_language

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('set_language/', set_language, name='set_language'),
    path('admin/', admin.site.urls),
    path('DeCharla/', include('DeCharla.urls')),
    path('favicon.ico/', RedirectView.as_view(url=staticfiles_storage.url("DeCharla/favicon.ico")))
]

DeCharla/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.
class Contrasena(models.Model):
    contrasena = models.TextField()

    def __str__(self):
        return str(self.id) + ": " + self.contrasena

class Sesion(models.Model):
    cookie_user = models.CharField(max_length=32)

    def __str__(self):
        return self.cookie_user

class Sala(models.Model):
    creador = models.ForeignKey(Sesion, on_delete=models.CASCADE)
    nombre = models.TextField(max_length=50)
    fecha = models.DateTimeField('visitado')
    votos = models.IntegerField(default=0)

    def __str__(self):
        return self.nombre

class Voto(models.Model):
    sala = models.ForeignKey(Sala, on_delete=models.CASCADE)
    sesion = models.ForeignKey(Sesion, on_delete=models.CASCADE)
    megusta = models.BooleanField(default=False)

    def __str(self):
        return self.sala.nombre + ": " + self.sesion.cookie_user

class UltimaVisita(models.Model):
    sesion = models.ForeignKey(Sesion, on_delete=models.CASCADE )
    last_visit = models.DateTimeField(auto_now=True)
    sala = models.ForeignKey(Sala, on_delete=models.CASCADE)
    mensajes_no_leidos = models.PositiveIntegerField(default=0)

    def __str__(self):
        return str(self.sala) + '-->' +  str(self.last_visit)

class Mensaje(models.Model):
    creador = models.CharField(max_length=100)
    contenido = models.TextField()
    fecha = models.DateTimeField('publicado', auto_now_add=True)
    sala = models.ForeignKey(Sala, on_delete=models.CASCADE)
    es_url = models.BooleanField(default=False)

    def __str__(self):
        return self.contenido


class Configuracion(models.Model):
    sesion = models.OneToOneField(Sesion, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    TAMANO_FUENTE_CHOICES = [
        (12, _('Pequeño')),
        (16, _('Mediano')),
        (20, _('Grande')),
    ]
    tamano_fuente = models.PositiveIntegerField(choices=TAMANO_FUENTE_CHOICES, default=12)
    TIPO_FUENTE_CHOICES = [
        ('Arial', 'Arial'),
        ('Times New Roman', 'Times New Roman'),
        ('Verdana', 'Verdana'),
    ]
    tipo_fuente = models.CharField(max_length=50, choices=TIPO_FUENTE_CHOICES, default='Arial')

    def __str__(self):
        return self.nombre

DeCharla/forms.py
from django.utils.translation import gettext_lazy as _
from django import forms
from .models import Mensaje, Configuracion

class MensajeForm(forms.ModelForm):
    contenido = forms.CharField(widget=forms.Textarea, label=_('Contenido:'))
    es_url = forms.BooleanField(required=False, label=_('Seleccionar si el mensaje es una url:'))
    class Meta:
        model = Mensaje
        fields = ['contenido', 'es_url']

class ConfiguracionForm(forms.Form):
    nombre = forms.CharField(label=_('Nombre'), max_length=100)
    tamano_fuente = forms.ChoiceField(label=_('Tamaño de Fuente'), choices=Configuracion.TAMANO_FUENTE_CHOICES)
    tipo_fuente = forms.ChoiceField(label=_('Tipo de Fuente'), choices=Configuracion.TIPO_FUENTE_CHOICES)

class SalaForm(forms.Form):
    nombre_sala = forms.CharField(label=_('Nombre de la sala'), max_length=100)

DeCharla/views.py
import secrets
from datetime import timedelta
from xml.dom import minidom
from django.utils import translation
from django.contrib.auth import logout
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, HttpResponseBadRequest, Http404
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import render
from django.template import loader
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from .forms import MensajeForm, ConfiguracionForm, SalaForm
from django.db.models.signals import post_save
from django.dispatch import receiver
from .models import Sala, Mensaje, Configuracion, Sesion, Contrasena, UltimaVisita, Voto


# Create your views here.

def configuracion_default(sesion):
    configuracion = Configuracion(sesion=sesion, nombre="Anónimo",
                                  tamano_fuente=12, tipo_fuente='Arial')
    configuracion.save()
    return configuracion

@csrf_exempt
def manejar_login(request):
    if request.method == 'POST':
        if not 'cookie_user' in request.COOKIES:
            contrasena = request.POST.get('contrasena')
            try:
                expiration = timezone.now() + timedelta(days=3650)
                Contrasena.objects.get(contrasena=contrasena)
                auth_token = secrets.token_hex(16)
                sesion = Sesion(cookie_user=auth_token)
                sesion.save()
                configuracion = configuracion_default(sesion)
                configuracion.save()
                response = HttpResponseRedirect('/DeCharla/')
                response.status_code = 301
                response.set_cookie('cookie_user', auth_token, expires=expiration)
                return response

            except Contrasena.DoesNotExist:
                return HttpResponse('Unauthorized', status=401)

        else:
            return HttpResponseRedirect('/DeCharla/')
    else:
        return render(request, 'registration/login.html')



def sala_dinamica(request, sala):
    if 'cookie_user' in request.COOKIES:
        cookie_user = request.COOKIES['cookie_user']
        configuracion = Configuracion.objects.get(sesion__cookie_user=cookie_user)
    else:
        return redirect('login')

    try:
        Sala.objects.get(nombre=sala)
        form = MensajeForm()
        total_mensajes_textuales, total_mensajes_imagenes, total_salas_activas = pie_pagina()
        template = loader.get_template('DeCharla/sala_dinamica.html')
        contexto = {
            'sala': sala,
            'form': form,
            'configuracion': configuracion,
            'total_mensajes_textuales': total_mensajes_textuales,
            'total_mensajes_imagenes': total_mensajes_imagenes,
            'total_salas_activas': total_salas_activas,
        }
        return HttpResponse(template.render(contexto, request))

    except Sala.DoesNotExist:
        raise Http404("Lo siento el nombre de recurso introducido para la sala no existe. Inténtelo de nuevo.")

def manejar_logout(request):
    logout(request)

    response = redirect('login')
    response.delete_cookie('cookie_user')

    return response

@csrf_exempt
def set_language(request):
    if request.method == 'POST' and 'language' in request.POST:
        language = request.POST['language']
        translation.activate(language)
        request.session[translation.LANGUAGE_SESSION_KEY] = language

    return redirect(request.POST.get('next') or '/')

def sala_json(request, sala):
    sala = get_object_or_404(Sala, nombre=sala)
    mensajes = Mensaje.objects.filter(sala=sala)

    mensaje_list = []
    for mensaje in mensajes:
        mensaje_dict = {
            'author': mensaje.creador,
            'text': mensaje.contenido,
            'isimg': mensaje.es_url,
            'date': mensaje.fecha.strftime('%Y-%m-%d:%H:%M:%S')
        }
        mensaje_list.append(mensaje_dict)

    return JsonResponse(mensaje_list, safe=False)

@csrf_exempt
def crear_sala(request):
    form_sala = SalaForm(request.POST)
    if request.method == 'POST':
        if form_sala.is_valid():
            nombre_sala = form_sala.cleaned_data['nombre_sala']
            if Sala.objects.filter(nombre=nombre_sala).exists():
                return redirect('manejar_salas', sala=nombre_sala)

            fecha_actual = timezone.now()
            cookie_user = request.COOKIES['cookie_user']
            sesion = Sesion.objects.get(cookie_user=cookie_user)
            sala = Sala(nombre=nombre_sala, fecha=fecha_actual, creador=sesion)
            sala.save()
            sesiones = Sesion.objects.all()
            for sesion in sesiones:
                if not Voto.objects.filter(sesion=sesion, sala=sala):
                    voto = Voto(sesion=sesion, sala=sala, megusta=False)
                    voto.save()

            return redirect('manejar_salas', sala=nombre_sala)
        else:
            return HttpResponse("Introduzca un nombre de sala válido por favor.")

def help(request):
    if 'cookie_user' in request.COOKIES:
        cookie_user = request.COOKIES['cookie_user']
        configuracion = Configuracion.objects.get(sesion__cookie_user=cookie_user)
    else:
        return redirect('login')
    form_sala = SalaForm(request.POST)
    total_mensajes_textuales, total_mensajes_imagenes, total_salas_activas = pie_pagina()

    template = loader.get_template('DeCharla/help.html')
    contexto = {
        'form_sala': form_sala,
        'configuracion': configuracion,
        'total_mensajes_textuales': total_mensajes_textuales,
        'total_mensajes_imagenes': total_mensajes_imagenes,
        'total_salas_activas': total_salas_activas,
    }
    return HttpResponse(template.render(contexto, request))


@receiver(post_save, sender=Sesion)
def crear_votos_sesion_existente(sender, instance, created, **kwargs):
    if created:
        salas = Sala.objects.all()
        for sala in salas:
            sala.save()
            Voto.objects.create(sesion=instance, sala=sala, megusta=False)

post_save.connect(crear_votos_sesion_existente, sender=Sesion)


@csrf_exempt
def index(request):
    if 'cookie_user' in request.COOKIES:
        cookie_user = request.COOKIES['cookie_user']
        configuracion = Configuracion.objects.get(sesion__cookie_user=cookie_user)
    else:
        return redirect('login')

    sala_list = Sala.objects.all()
    sesion_obj = Sesion.objects.get(cookie_user=cookie_user)
    salas_con_mensajes = []

    for sala in sala_list:
        num_mensajes = Mensaje.objects.filter(sala=sala).count()
        try:
            ultima_visita = UltimaVisita.objects.filter(sesion=sesion_obj, sala=sala).first()
            if ultima_visita:
                mensajes_no_leidos = Mensaje.objects.filter(sala=sala, fecha__gt=ultima_visita.last_visit).count()
                if mensajes_no_leidos > 0:
                    ultima_visita.mensajes_no_leidos = mensajes_no_leidos
                    ultima_visita.save()
            else:
                mensajes_no_leidos = num_mensajes

        except UltimaVisita.DoesNotExist:
            mensajes_no_leidos = num_mensajes

        salas_con_mensajes.append((sala, num_mensajes, mensajes_no_leidos))

    total_mensajes_textuales, total_mensajes_imagenes, total_salas_activas = pie_pagina()
    form_sala = SalaForm(request.POST)
    votos = Voto.objects.filter(sesion=sesion_obj)
    template = loader.get_template('DeCharla/index.html')
    contexto = {
        'sala_list': sala_list,
        'form_sala': form_sala,
        'votos': votos,
        'salas_con_mensajes': salas_con_mensajes,
        'configuracion': configuracion,
        'total_mensajes_textuales': total_mensajes_textuales,
        'total_mensajes_imagenes': total_mensajes_imagenes,
        'total_salas_activas': total_salas_activas,
    }
    return HttpResponse(template.render(contexto, request))


def pie_pagina():
    mensajes_textuales = Mensaje.objects.filter(es_url=False)
    mensajes_imagenes = Mensaje.objects.filter(es_url=True)
    total_mensajes_textuales = mensajes_textuales.count()
    total_mensajes_imagenes = mensajes_imagenes.count()
    total_salas_activas = Sala.objects.count()
    return total_mensajes_textuales, total_mensajes_imagenes, total_salas_activas

def doGET(sala, cookie_user, sala_obj):
    mensajes_list = Mensaje.objects.filter(sala__nombre=sala).order_by('-fecha')
    sesion_obj = get_object_or_404(Sesion, cookie_user=cookie_user)
    ultima_visita, created = UltimaVisita.objects.get_or_create(sesion=sesion_obj, sala=sala_obj)

    if created:
        mensajes_no_leidos = mensajes_list.count()
    else:
        mensajes_no_leidos = mensajes_list.filter(fecha__gt=ultima_visita.last_visit).count()

    ultima_visita.last_visit = timezone.now()
    ultima_visita.save()

    response = HttpResponse()
    cookie_key = 'last_visit_{}'.format(sala.replace(' ', '_'))
    response.set_cookie(cookie_key, timezone.now().strftime('%Y-%m-%d %H:%M:%S'))

    return mensajes_list, mensajes_no_leidos


def doPOST_mensaje(request, sesion, sala, sala_obj, configuracion):
    form = MensajeForm(request.POST)
    if form.is_valid():
        mensaje = form.save(commit=False)
        mensaje.sala = sala_obj
        mensaje.creador = configuracion.nombre
        mensaje.save()
        ultima_visita = UltimaVisita.objects.get(sesion=sesion, sala=sala_obj)
        ultima_visita.save()

        return redirect('manejar_salas', sala=sala)

def doPUT(request, sala):
    sala_obj = Sala.objects.get(nombre=sala)
    xml_data = request.body
    try:
        dom = minidom.parseString(xml_data)
        messages = dom.getElementsByTagName('message')

        for message in messages:
            is_image = message.getAttribute('isimg')
            text_elem = message.getElementsByTagName('text')[0]
            text = text_elem.firstChild.nodeValue.strip()
            author_elem = message.getElementsByTagName('author')[0]
            author = author_elem.firstChild.nodeValue.strip()

DeCharla/templates/DeCharla/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>DeCharla</title>
    <link rel="icon" href="{% static 'DeCharla/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'DeCharla/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'DeCharla/style.css/' %}">
    <style>
        body {
            font-size: {{ configuracion.tamano_fuente }}px;
            font-family: {{ configuracion.tipo_fuente }};
            background-color: #b9adc7
        }

        header {
            background-image: url("{% static 'DeCharla/banner/bannerDeCharla.jpg' %}");
        }
    </style>
</head>
<body>
<link rel="stylesheet" type="text/css" href="{% static 'DeCharla/style.css/' %}">
    <header class="bg-primary text-white">
        <a href="/DeCharla/" class="decharla">DeCharla</a>
    </header>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <ul class="navbar-nav mr-auto">
            <div id="configuracion">
              <li class="nav-item">
                <a class="nav-link" href="/DeCharla/configuracion">{%  trans "Configuración" %}</a>
              </li>
            </div>
            <div id="principal">
              <li class="nav-item">
                <a class="nav-link" href="/DeCharla/">{% trans 'Principal' %}</a>
              </li>
            </div>
            <div id="admin">
              <li class="nav-item">
                <a class="nav-link" href="/admin/">Admin</a>
              </li>
            </div>
            <div id="help">
              <li class="nav-item">
                <a class="nav-link" href="/DeCharla/help">{% trans 'Ayuda' %}</a>
              </li>
            </div>
            <script>
              var currentUrl = window.location.pathname;

              if (currentUrl === "/DeCharla/") {
                document.getElementById("principal").style.display = "none";
              } else if (currentUrl === "/DeCharla/configuracion") {
                document.getElementById("configuracion").style.display = "none";
              } else if (currentUrl === "/admin/") {
                document.getElementById("admin").style.display = "none";
              } else if (currentUrl === "/DeCharla/help") {
                document.getElementById("help").style.display = "none";
              }
            </script>
            <a href="{% url 'logout' %}" class="btn btn-secondary logout-link">{%  trans 'Cerrar sesión' %}</a>
            </ul>

        </div>
    </nav>

    <main class="container">
        <div class="row">
            <div class="col-lg-9">
                {% block body %}
                {% endblock %}
            </div>
            <div class="col-lg-3 position-fixed bottom-0 end-0">
                <div class="custom-bg">
                    <p class="fs-5 text-light"> {% trans 'Hola' %} {{ configuracion.nombre }}!</p>
                    <p class="fs-6 text-light">{%  trans 'Introduce un nombre para crear una sala o bien para entrar a una ya existente si así lo desea.' %}</p>
                    <form method="post" action="{% url 'crear_sala' %}" class="mt-4">
                        {% csrf_token %}
                        <div class="mb-3">
                            <input type="text" class="form-control" name="nombre_sala" placeholder="{% trans 'Nombre de la sala' %}">
                        </div>
                        <button type="submit" class="btn btn-light">{%  trans 'Crear Sala' %}</button>
                    </form>
                </div>
            </div>
            </div>
        </div>
    </main>
    <script src="{% static 'DeCharla/js/bootstrap.min.js' %}"></script>

    <footer class="bg-light">
        <div class="container">
            <p class="text-dark">{% trans 'Mensajes' %}: {{ total_mensajes_textuales }} ({% trans 'textuales' %}), {{ total_mensajes_imagenes }} ({% trans 'imágenes' %}).
                {% trans 'Salas activas' %}: {{ total_salas_activas }}</p>
        </div>
    </footer>

</body>
</html>

DeCharla/templates/DeCharla/configuracion.html
{% extends "DeCharla/base.html" %}
{%  load i18n %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% trans 'Página de Configuración' %}</title>
</head>
<body>
{% block body %}
    <h2 class="text-center mb-4" style="text-transform: uppercase; background-color: #800080; color: white; padding: 10px;">{% trans 'PÁGINA DE CONFIGURACIÓN' %}</h2>
    <form class="mt-4" method="post">
    {% csrf_token %}

    <div class="form-group">
        <div class="row">
            <div class="col-md-12">
                {{ form.as_p }}
            </div>
        </div>
    </div>

    <div>
        <button type="submit" class="btn btn-primary" style="background-color: #8650be;">{% trans 'Guardar' %}</button>
    </div>
    </form>

    <div class="mt-4">
    <h2 style="color: purple;">{% trans 'Configuración actual' %}</h2>
    <div class="row">
        <div class="col-md-6">
            <p><strong>{% trans 'Nombre' %}:</strong> {{ configuracion.nombre }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <p><strong>{% trans 'Tamaño de fuente' %}:</strong> {{ configuracion.get_tamano_fuente_display }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <p><strong>{% trans 'Tipo de fuente' %}:</strong> {{ configuracion.get_tipo_fuente_display }}</p>
        </div>
    </div>
    </div>


{% endblock %}
</body>
</html>

DeCharla/templates/DeCharla/help.html
{% extends "DeCharla/base.html" %}
{%  load i18n %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% trans 'PÁGINA DE AYUDA' %}</title>
</head>
<body>
{% block body %}
    <h2 class="text-center mb-4" style="text-transform: uppercase; background-color: #800080; color: white; padding: 10px;">{% trans 'PÁGINA DE AYUDA' %}</h2>

    <p>{%  trans 'Hola, si estás aquí es porque necesitas algo de ayuda. Espero que el siguiente resumen te ayude, pero si necesitas más asistencia, no dudes en contactarme vía email (hafsaeljauhari@gmail.com).' %}.</p>

    <h2>1.{% trans '¿En qué consiste la aplicación?' %}</h2>
    <p>{% trans 'La aplicación DeCharla consiste en un chat en el que cualquier persona puede escribir mensajes. El chat se estructura por salas que pueden tratar diversos temas, hobbies, aspiraciones... o simplemente ser de libre mensajería.' %}</p>

    <h2>2.{% trans '¿Quién puede crear salas?' %}</h2>
    <p>{% trans 'Tal y como está configurada la aplicación,  pueden crear salas todos aquellos usuarios autenticados a través de una contraseña válida proporcionada por el administrador de la aplicación.' %}.</p>

    <h2>3.{% trans '¿Quién puede escribir mensajes?' %}</h2>
    <p>{% trans 'Tal y como está configurada la aplicación,  pueden crear salas todos aquellos usuarios autenticados a través de una contraseña válida proporcionada por el administrador de la aplicación.' %}.</p>

    <h2>4. {% trans '¿Quién creó la aplicación?' %}</h2>
    <p>{% trans 'La aplicación fue creada por la estudiante Hafsa El Jauhari Al Jaouhari durante el periodo de Mayo/Junio de 2023.' %}</p>
{% endblock %}

</body>
</html>

DeCharla/templates/DeCharla/index.html
{% extends "DeCharla/base.html" %}
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>{% trans 'PÁGINA PRINCIPAL' %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'DeCharla/style.css/' %}">
</head>

<body>
{% block body %}
<div class="container">
    <h2 class="text-center mb-4" style="text-transform: uppercase; background-color: #800080; color: white; padding: 10px;">{% trans 'SALAS DISPONIBLES' %}</h2>

    {% if sala_list %}
    <div class="row">
        {% for sala, num_mensajes, noleidos in salas_con_mensajes %}
            <div class="col-md-6">
                <div class="card mb-4">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="/DeCharla/{{ sala.nombre }}" class="text-decoration-none text-dark fw-bold">{{ sala.nombre }}</a>
                        </h5>
                        <p class="card-title">
                            <a href="/DeCharla/sala_dinamica/{{ sala.nombre }}" class="text-decoration-none text-dark fw-bold">{%  trans 'Sala Dinámica' %}</a>
                        </p>
                        <p class="card-title">
                            <a href="/DeCharla/sala_json/{{ sala.nombre }}" class="text-decoration-none text-dark fw-bold">{%  trans 'Sala Json' %}</a>
                        </p>
                        <p class="card-text mb-2">{% trans 'Mensajes totales' %}: <span class="badge bg-primary">{{ num_mensajes }}</span></p>
                        <p class="card-text mb-0">{%  trans 'Mensajes no leídos' %}:
                            {% if noleidos > 0 %}
                                <span class="badge bg-danger text-white"><strong>{{ noleidos }}</strong></span>
                            {% else %}
                                <span class="badge bg-success text-white"><strong>{{ noleidos }}</strong></span>
                            {% endif %}
                        <p class="card-text mb-2">{%  trans 'Me gustas totales' %}: <span class="badge bg-primary">{{ sala.votos }}</span></p>
                        {% for voto in votos %}
                            {% if voto.sala == sala %}
                                {% if not voto.megusta %}
                                    <div class="sala">
                                        <span class="like-icon" style="cursor: pointer" onclick="likeSala('{{ sala.nombre }}')">&#x1F44D;
                                            <i class="fa fa-thumbs-up"></i>{%  trans 'Me gusta' %} </span>
                                    </div>
                                {% else %}
                                    <div class="sala">
                                        <span class="like-icon" style="cursor: pointer" onclick="dislikeSala('{{ sala.nombre }}')">&#x2716;
                                            <i class="fa fa-thumbs-down"></i> {%  trans 'Ya NO me gusta' %} </span>
                                    </div>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% else %}
        <p class="text-center">{%  trans 'No hay salas creadas' %}</p>
    {% endif %}

<script>
    function likeSala(sala) {
  const form = document.createElement('form');
  form.method = 'POST';
  form.action = 'votar/';

  const inputAction = document.createElement('input');
  inputAction.type = 'hidden';
  inputAction.name = 'action';
  inputAction.value = 'votar/';

  const inputSala = document.createElement('input');
  inputSala.type = 'hidden';
  inputSala.name = 'sala';
  inputSala.value = sala;

  form.appendChild(inputAction);
  form.appendChild(inputSala);

  document.body.appendChild(form);
  form.submit();
}

function dislikeSala(sala) {
  const form = document.createElement('form');
  form.method = 'POST';
  form.action = 'desvotar/';

  const inputAction = document.createElement('input');
  inputAction.type = 'hidden';
  inputAction.name = 'action';
  inputAction.value = 'desvotar/';

  const inputSala = document.createElement('input');
  inputSala.type = 'hidden';
  inputSala.name = 'sala';
  inputSala.value = sala;
  form.appendChild(inputAction);
  form.appendChild(inputSala);
  document.body.appendChild(form);
  form.submit();
}

</script>
</div>

{% endblock %}

</body>
</html>

DeCharla/templates/DeCharla/sala.html
{% extends "DeCharla/base.html" %}
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% trans 'PÁGINA SALA' %}</title>
</head>

<body>
{% block body %}
    <div class="chat-container">
    <h2 class="chat-title">{{ sala }}</h2>

    {% if mensajes_list %}
    <ul>
      {% for mensaje in mensajes_list %}
        <li class="chat-message">
          <span class="message-creator">{{ mensaje.creador }}</span>:

          {% if mensaje.es_url %}
            <img src="{{ mensaje.contenido }}" alt="Imagen">
          {% else %}
            {{ mensaje.contenido }}
          {% endif %}

          <span class="message-date">{{ mensaje.fecha }}</span>
        </li>
      {% endfor %}
    </ul>
    {% else %}
      <p class="no-messages">{% trans 'No hay mensajes añadidos' %}</p>
    {% endif %}
  </div>


    <h2 style="color: #170534;">{% trans  'Añadir mensaje' %}</h2>

    <form class="mt-4" method="post" action="{% url 'manejar_salas' sala=sala %}" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="form-group">
        {{ form.as_p }}
      </div>

      <div class="text-center">
        <button type="submit" class="btn btn-primary" style="background-color: #683c9b; border-color: #170534;">{% trans  'Añadir mensaje' %}</button>
      </div>
    </form>

{% endblock %}
</body>
</html>

DeCharla/templates/DeCharla/sala_dinamica.html
{% extends "DeCharla/base.html" %}
{% load static %}
{%  load i18n %}
<!DOCTYPE html>
<head>
    <title>{% trans 'PÁGINA SALA' %}</title>
    <link rel="icon" href="{% static 'DeCharla/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'DeCharla/css/bootstrap.min.css' %}">
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8">

</head>
<body>
{%  block body %}

    <div class="chat-container">
    <h2 class="chat-title">{{ sala }}</h2>

    <div class="container-fluid">
    <div class="row">
        <div class="col-xxl-12">
            <div id="messages"></div>
            <script>
                const url_messages = '{% url 'sala_json' sala=sala %}';
            </script>
            <script type="text/javascript" src='{% static "DeCharla/script.js" %}' ></script>
        </div>
    </div>
    </div>
</div>
{% endblock %}
</body>